begin;

insert into app.permissions (code, description) values
  ('transfers.read', 'View branch transfers'),
  ('transfers.manage', 'Create, dispatch, and receive branch transfers')
on conflict (code) do update set description = excluded.description;

create table app.stock_transfers (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references app.tenants(id) on delete restrict,
  transfer_number text not null, source_location_id uuid not null, destination_location_id uuid not null,
  status text not null default 'draft' check (status in ('draft','dispatched','partially_received','received','cancelled')),
  created_by uuid not null references auth.users(id) on delete restrict, dispatched_at timestamptz, received_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (tenant_id,id), unique (tenant_id,transfer_number),
  foreign key (tenant_id,source_location_id) references app.locations(tenant_id,id) on delete restrict,
  foreign key (tenant_id,destination_location_id) references app.locations(tenant_id,id) on delete restrict,
  constraint stock_transfers_different_locations check (source_location_id <> destination_location_id),
  constraint stock_transfers_number_not_blank check (btrim(transfer_number) <> '')
);
create table app.stock_transfer_items (
  id uuid primary key default gen_random_uuid(), tenant_id uuid not null references app.tenants(id) on delete restrict,
  transfer_id uuid not null, variant_id uuid not null, requested_quantity numeric(18,3) not null check (requested_quantity > 0),
  received_quantity numeric(18,3) not null default 0 check (received_quantity >= 0 and received_quantity <= requested_quantity),
  unit_cost numeric(18,2) not null check (unit_cost >= 0), created_at timestamptz not null default now(), unique(tenant_id,id),
  unique(tenant_id,transfer_id,variant_id), foreign key (tenant_id,transfer_id) references app.stock_transfers(tenant_id,id) on delete restrict,
  foreign key (tenant_id,variant_id) references app.product_variants(tenant_id,id) on delete restrict
);
create index stock_transfers_tenant_status_idx on app.stock_transfers(tenant_id,status,created_at desc);
alter table app.stock_transfers enable row level security;
alter table app.stock_transfer_items enable row level security;
revoke all on table app.stock_transfers, app.stock_transfer_items from public, anon, authenticated, hcs_hyperdrive;
insert into app.role_permissions(tenant_id,role_id,permission_code)
select role.tenant_id,role.id,permission.code from app.roles role cross join app.permissions permission
where lower(role.code::text)='owner' and permission.code in ('transfers.read','transfers.manage') on conflict do nothing;
create function app.initialize_owner_transfer_permissions() returns trigger language plpgsql security definer set search_path='' as $$
begin if lower(new.code::text)='owner' then insert into app.role_permissions(tenant_id,role_id,permission_code) values(new.tenant_id,new.id,'transfers.read'),(new.tenant_id,new.id,'transfers.manage') on conflict do nothing; end if; return new; end; $$;
revoke all on function app.initialize_owner_transfer_permissions() from public,anon,authenticated;
create trigger roles_initialize_transfer_permissions after insert on app.roles for each row execute function app.initialize_owner_transfer_permissions();
create trigger stock_transfers_set_updated_at before update on app.stock_transfers for each row execute function app.set_updated_at();

create function app.list_transfer_context(p_actor_user_id uuid,p_tenant_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_allowed boolean;
begin
 select m.is_owner or exists(select 1 from app.membership_roles mr join app.role_permissions rp on rp.tenant_id=mr.tenant_id and rp.role_id=mr.role_id where mr.tenant_id=m.tenant_id and mr.user_id=m.user_id and rp.permission_code in('transfers.read','transfers.manage')) into v_allowed from app.tenant_memberships m where m.tenant_id=p_tenant_id and m.user_id=p_actor_user_id and m.status='active';
 if not found or not v_allowed then raise exception using errcode='HCS50',message='Transfer access is not allowed'; end if;
 return jsonb_build_object('locations',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'code',l.code,'name',l.name) order by l.name) from app.locations l where l.tenant_id=p_tenant_id and l.is_active),'[]'::jsonb),'variants',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'productName',p.name,'variantName',v.name,'sku',v.sku::text,'defaultUnitCostMinor',case when v.unit_cost is null then null else round(v.unit_cost*100)::bigint end) order by p.name,v.name) from app.product_variants v join app.products p on p.tenant_id=v.tenant_id and p.id=v.product_id where v.tenant_id=p_tenant_id and v.is_active and p.status='active'),'[]'::jsonb),'transfers',coalesce((select jsonb_agg(jsonb_build_object('id',t.id,'transferNumber',t.transfer_number,'sourceLocationId',t.source_location_id,'sourceLocationName',src.name,'destinationLocationId',t.destination_location_id,'destinationLocationName',dst.name,'status',t.status,'createdAt',t.created_at,'items',(select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'variantId',i.variant_id,'productName',p.name,'variantName',v.name,'sku',v.sku::text,'requestedQuantityMilli',round(i.requested_quantity*1000)::bigint,'receivedQuantityMilli',round(i.received_quantity*1000)::bigint,'unitCostMinor',round(i.unit_cost*100)::bigint) order by p.name,v.name),'[]'::jsonb) from app.stock_transfer_items i join app.product_variants v on v.tenant_id=i.tenant_id and v.id=i.variant_id join app.products p on p.tenant_id=v.tenant_id and p.id=v.product_id where i.tenant_id=t.tenant_id and i.transfer_id=t.id)) order by t.created_at desc) from app.stock_transfers t join app.locations src on src.tenant_id=t.tenant_id and src.id=t.source_location_id join app.locations dst on dst.tenant_id=t.tenant_id and dst.id=t.destination_location_id where t.tenant_id=p_tenant_id),'[]'::jsonb));
end; $$;

create function app.create_stock_transfer(p_actor_user_id uuid,p_tenant_id uuid,p_transfer_number text,p_source_location_id uuid,p_destination_location_id uuid,p_items jsonb,p_idempotency_key text,p_request_hash text,p_request_id text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_id uuid; v_item jsonb; v_count int:=0; v_existing app.idempotency_records%rowtype; v_response jsonb;
begin
 if not exists(select 1 from app.tenant_memberships m where m.tenant_id=p_tenant_id and m.user_id=p_actor_user_id and m.status='active' and(m.is_owner or exists(select 1 from app.membership_roles mr join app.role_permissions rp on rp.tenant_id=mr.tenant_id and rp.role_id=mr.role_id where mr.tenant_id=m.tenant_id and mr.user_id=m.user_id and rp.permission_code='transfers.manage'))) then raise exception using errcode='HCS50',message='Transfer management is not allowed'; end if;
 if p_transfer_number is null or btrim(p_transfer_number)='' or jsonb_array_length(p_items)<1 or p_source_location_id=p_destination_location_id then raise exception using errcode='HCS51',message='Transfer details are invalid'; end if;
 if not exists(select 1 from app.locations where tenant_id=p_tenant_id and id=p_source_location_id and is_active) or not exists(select 1 from app.locations where tenant_id=p_tenant_id and id=p_destination_location_id and is_active) then raise exception using errcode='HCS52',message='Transfer location was not found'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_tenant_id::text||':transfer:'||p_idempotency_key,0));
 select * into v_existing from app.idempotency_records where tenant_id=p_tenant_id and operation='transfer.create' and idempotency_key=p_idempotency_key;
 if found then if v_existing.request_hash<>p_request_hash then raise exception using errcode='HCS08',message='Idempotency key conflict'; end if; if v_existing.completed_at is not null then return v_existing.response_body; end if;
 else insert into app.idempotency_records(tenant_id,operation,idempotency_key,request_hash,locked_until,expires_at) values(p_tenant_id,'transfer.create',p_idempotency_key,p_request_hash,now()+interval '1 minute',now()+interval '24 hours'); end if;
 insert into app.stock_transfers(tenant_id,transfer_number,source_location_id,destination_location_id,created_by) values(p_tenant_id,btrim(p_transfer_number),p_source_location_id,p_destination_location_id,p_actor_user_id) returning id into v_id;
 for v_item in select * from jsonb_array_elements(p_items) loop
   if (v_item->>'variantId') is null or (v_item->>'quantityMilli')::bigint<=0 then raise exception using errcode='HCS51',message='Transfer item is invalid'; end if;
   if not exists(select 1 from app.product_variants v join app.products p on p.tenant_id=v.tenant_id and p.id=v.product_id where v.tenant_id=p_tenant_id and v.id=(v_item->>'variantId')::uuid and v.is_active and p.status='active') then raise exception using errcode='HCS53',message='Transfer variant was not found'; end if;
   insert into app.stock_transfer_items(tenant_id,transfer_id,variant_id,requested_quantity,unit_cost) select p_tenant_id,v_id,(v_item->>'variantId')::uuid,(v_item->>'quantityMilli')::numeric/1000,coalesce(b.average_unit_cost,0) from app.inventory_balances b where b.tenant_id=p_tenant_id and b.location_id=p_source_location_id and b.variant_id=(v_item->>'variantId')::uuid;
   if not found then insert into app.stock_transfer_items(tenant_id,transfer_id,variant_id,requested_quantity,unit_cost) values(p_tenant_id,v_id,(v_item->>'variantId')::uuid,(v_item->>'quantityMilli')::numeric/1000,0); end if; v_count:=v_count+1;
 end loop;
 v_response:=jsonb_build_object('stockTransferId',v_id,'status','draft','itemCount',v_count); insert into audit.audit_events(tenant_id,request_id,actor_type,actor_id,action,entity_type,entity_id) values(p_tenant_id,p_request_id,'tenant_user',p_actor_user_id,'stock_transfer.created','stock_transfer',v_id); insert into integration.event_outbox(tenant_id,topic,aggregate_type,aggregate_id,payload) values(p_tenant_id,'stock_transfer.created','stock_transfer',v_id,v_response); update app.idempotency_records set response_status=201,response_body=v_response,completed_at=now(),locked_until=null where tenant_id=p_tenant_id and operation='transfer.create' and idempotency_key=p_idempotency_key; return v_response;
exception when unique_violation then raise exception using errcode='HCS54',message='Transfer number or item already exists'; end; $$;

create function app.dispatch_stock_transfer(p_actor_user_id uuid,p_tenant_id uuid,p_transfer_id uuid,p_idempotency_key text,p_request_hash text,p_request_id text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_t app.stock_transfers%rowtype; v_i app.stock_transfer_items%rowtype; v_b app.inventory_balances%rowtype; v_response jsonb;
begin
 if not exists(select 1 from app.tenant_memberships m where m.tenant_id=p_tenant_id and m.user_id=p_actor_user_id and m.status='active' and(m.is_owner or exists(select 1 from app.membership_roles mr join app.role_permissions rp on rp.tenant_id=mr.tenant_id and rp.role_id=mr.role_id where mr.tenant_id=m.tenant_id and mr.user_id=m.user_id and rp.permission_code='transfers.manage'))) then raise exception using errcode='HCS50',message='Transfer management is not allowed'; end if;
 perform pg_advisory_xact_lock(hashtextextended(p_tenant_id::text||':transfer:dispatch:'||p_transfer_id::text,0)); select * into v_t from app.stock_transfers where tenant_id=p_tenant_id and id=p_transfer_id for update; if not found then raise exception using errcode='HCS55',message='Transfer was not found'; end if; if v_t.status<>'draft' then raise exception using errcode='HCS56',message='Only draft transfers can be dispatched'; end if;
 for v_i in select * from app.stock_transfer_items where tenant_id=p_tenant_id and transfer_id=p_transfer_id loop select * into v_b from app.inventory_balances where tenant_id=p_tenant_id and location_id=v_t.source_location_id and variant_id=v_i.variant_id for update; if not found or v_b.on_hand-v_b.reserved<v_i.requested_quantity then raise exception using errcode='HCS57',message='Source stock is insufficient'; end if; update app.inventory_balances set on_hand=on_hand-v_i.requested_quantity,version=version+1,updated_at=now() where tenant_id=p_tenant_id and location_id=v_t.source_location_id and variant_id=v_i.variant_id; insert into app.inventory_balances(tenant_id,location_id,variant_id,in_transit,average_unit_cost,version) values(p_tenant_id,v_t.destination_location_id,v_i.variant_id,v_i.requested_quantity,v_i.unit_cost,1) on conflict(tenant_id,location_id,variant_id) do update set in_transit=app.inventory_balances.in_transit+excluded.in_transit,version=app.inventory_balances.version+1,updated_at=now(); insert into app.inventory_movements(tenant_id,location_id,variant_id,movement_type,quantity,unit_cost,source_type,source_reference,actor_user_id) values(p_tenant_id,v_t.source_location_id,v_i.variant_id,'TRANSFER_OUT',-v_i.requested_quantity,v_i.unit_cost,'stock_transfer',p_transfer_id::text,p_actor_user_id); end loop;
 update app.stock_transfers set status='dispatched',dispatched_at=now(),updated_at=now() where tenant_id=p_tenant_id and id=p_transfer_id; v_response=jsonb_build_object('stockTransferId',p_transfer_id,'status','dispatched'); insert into audit.audit_events(tenant_id,request_id,actor_type,actor_id,action,entity_type,entity_id) values(p_tenant_id,p_request_id,'tenant_user',p_actor_user_id,'stock_transfer.dispatched','stock_transfer',p_transfer_id); insert into integration.event_outbox(tenant_id,topic,aggregate_type,aggregate_id,payload) values(p_tenant_id,'stock_transfer.dispatched','stock_transfer',p_transfer_id,v_response); return v_response; end; $$;

create function app.receive_stock_transfer(p_actor_user_id uuid,p_tenant_id uuid,p_transfer_id uuid,p_items jsonb,p_idempotency_key text,p_request_hash text,p_request_id text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_t app.stock_transfers%rowtype; v_i app.stock_transfer_items%rowtype; v_b app.inventory_balances%rowtype; v_item jsonb; v_qty numeric; v_response jsonb; v_count int:=0;
begin
 if not exists(select 1 from app.tenant_memberships m where m.tenant_id=p_tenant_id and m.user_id=p_actor_user_id and m.status='active' and(m.is_owner or exists(select 1 from app.membership_roles mr join app.role_permissions rp on rp.tenant_id=mr.tenant_id and rp.role_id=mr.role_id where mr.tenant_id=m.tenant_id and mr.user_id=m.user_id and rp.permission_code='transfers.manage'))) then raise exception using errcode='HCS50',message='Transfer management is not allowed'; end if;
 select * into v_t from app.stock_transfers where tenant_id=p_tenant_id and id=p_transfer_id for update; if not found or v_t.status not in('dispatched','partially_received') then raise exception using errcode='HCS55',message='Transfer is not ready to receive'; end if;
 for v_item in select * from jsonb_array_elements(p_items) loop select * into v_i from app.stock_transfer_items where tenant_id=p_tenant_id and id=(v_item->>'stockTransferItemId')::uuid and transfer_id=p_transfer_id for update; if not found then raise exception using errcode='HCS58',message='Transfer item was not found'; end if; v_qty:=(v_item->>'quantityMilli')::numeric/1000; if v_qty is null or v_qty<=0 or v_qty>v_i.requested_quantity-v_i.received_quantity then raise exception using errcode='HCS59',message='Receipt exceeds transfer quantity'; end if; select * into v_b from app.inventory_balances where tenant_id=p_tenant_id and location_id=v_t.destination_location_id and variant_id=v_i.variant_id for update; update app.inventory_balances set in_transit=in_transit-v_qty,on_hand=on_hand+v_qty,average_unit_cost=coalesce(average_unit_cost,v_i.unit_cost),version=version+1,updated_at=now() where tenant_id=p_tenant_id and location_id=v_t.destination_location_id and variant_id=v_i.variant_id; update app.stock_transfer_items set received_quantity=received_quantity+v_qty where tenant_id=p_tenant_id and id=v_i.id; insert into app.inventory_movements(tenant_id,location_id,variant_id,movement_type,quantity,unit_cost,source_type,source_reference,actor_user_id) values(p_tenant_id,v_t.destination_location_id,v_i.variant_id,'TRANSFER_IN',v_qty,v_i.unit_cost,'stock_transfer',p_transfer_id::text,p_actor_user_id); v_count:=v_count+1; end loop;
 if not exists(select 1 from app.stock_transfer_items where tenant_id=p_tenant_id and transfer_id=p_transfer_id and received_quantity<requested_quantity) then update app.stock_transfers set status='received',received_at=now(),updated_at=now() where tenant_id=p_tenant_id and id=p_transfer_id; else update app.stock_transfers set status='partially_received',updated_at=now() where tenant_id=p_tenant_id and id=p_transfer_id; end if; select status into v_t.status from app.stock_transfers where tenant_id=p_tenant_id and id=p_transfer_id; v_response=jsonb_build_object('stockTransferId',p_transfer_id,'status',v_t.status,'itemCount',v_count); insert into audit.audit_events(tenant_id,request_id,actor_type,actor_id,action,entity_type,entity_id) values(p_tenant_id,p_request_id,'tenant_user',p_actor_user_id,'stock_transfer.received','stock_transfer',p_transfer_id); insert into integration.event_outbox(tenant_id,topic,aggregate_type,aggregate_id,payload) values(p_tenant_id,'stock_transfer.received','stock_transfer',p_transfer_id,v_response); return v_response; end; $$;

revoke all on function app.list_transfer_context(uuid,uuid),app.create_stock_transfer(uuid,uuid,text,uuid,uuid,jsonb,text,text,text),app.dispatch_stock_transfer(uuid,uuid,uuid,text,text,text),app.receive_stock_transfer(uuid,uuid,uuid,jsonb,text,text,text) from public,anon,authenticated;
grant execute on function app.list_transfer_context(uuid,uuid),app.create_stock_transfer(uuid,uuid,text,uuid,uuid,jsonb,text,text,text),app.dispatch_stock_transfer(uuid,uuid,uuid,text,text,text),app.receive_stock_transfer(uuid,uuid,uuid,jsonb,text,text,text) to hcs_hyperdrive;
commit;
