begin;
insert into app.permissions(code,description) values ('workforce.read','View employees, roles, locations, and registers'),('workforce.manage','Manage employees, assignments, locations, and registers') on conflict(code) do update set description=excluded.description;

create table app.employee_pos_credentials(tenant_id uuid not null,employee_id uuid not null,pin_hash text not null,pin_changed_at timestamptz not null default now(),failed_attempts integer not null default 0 check(failed_attempts>=0),locked_until timestamptz,primary key(tenant_id,employee_id),foreign key(tenant_id,employee_id) references app.employees(tenant_id,id) on delete restrict);
create table app.employee_roles(tenant_id uuid not null,employee_id uuid not null,role_id uuid not null,created_at timestamptz not null default now(),primary key(tenant_id,employee_id,role_id),foreign key(tenant_id,employee_id) references app.employees(tenant_id,id) on delete restrict,foreign key(tenant_id,role_id) references app.roles(tenant_id,id) on delete restrict);
create table app.registers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id) on delete restrict,location_id uuid not null,name text not null,code extensions.citext not null,status text not null default 'active' check(status in('active','inactive')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,id),unique(tenant_id,code),foreign key(tenant_id,location_id) references app.locations(tenant_id,id) on delete restrict,constraint registers_name_not_blank check(btrim(name)<>''),constraint registers_code_not_blank check(btrim(code::text)<>''));
create trigger registers_set_updated_at before update on app.registers for each row execute function app.set_updated_at();
alter table app.employee_pos_credentials enable row level security; alter table app.employee_roles enable row level security; alter table app.registers enable row level security;
revoke all on table app.employee_pos_credentials,app.employee_roles,app.registers from public,anon,authenticated,hcs_hyperdrive;

insert into app.roles(tenant_id,code,name,is_system_template) select t.id,x.code,x.name,true from app.tenants t cross join(values('admin','Admin'),('manager','Manager'),('cashier','Cashier'),('inventory_staff','Inventory Staff')) x(code,name) on conflict(tenant_id,code) do nothing;
insert into app.role_permissions(tenant_id,role_id,permission_code) select r.tenant_id,r.id,p.code from app.roles r join app.permissions p on p.code=any(case lower(r.code::text) when 'admin' then array['workforce.read','workforce.manage','locations.manage','inventory.read','inventory.manage','purchasing.read','purchasing.manage','transfers.read','transfers.manage'] when 'manager' then array['workforce.read','inventory.read','inventory.manage','purchasing.read','purchasing.manage','transfers.read','transfers.manage'] when 'cashier' then array['inventory.read'] when 'inventory_staff' then array['inventory.read','inventory.manage','purchasing.read','transfers.read','transfers.manage'] else array[]::text[] end) where lower(r.code::text) in('admin','manager','cashier','inventory_staff') on conflict do nothing;
insert into app.role_permissions(tenant_id,role_id,permission_code) select r.tenant_id,r.id,p.code from app.roles r cross join app.permissions p where lower(r.code::text)='owner' and p.code in('workforce.read','workforce.manage') on conflict do nothing;

create function app.list_workforce_context(p_actor_user_id uuid,p_tenant_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
begin if not exists(select 1 from app.tenant_memberships m where m.tenant_id=p_tenant_id and m.user_id=p_actor_user_id and m.status='active' and(m.is_owner or exists(select 1 from app.membership_roles mr join app.role_permissions rp on rp.tenant_id=mr.tenant_id and rp.role_id=mr.role_id where mr.tenant_id=m.tenant_id and mr.user_id=m.user_id and rp.permission_code in('workforce.read','workforce.manage')))) then raise exception using errcode='HCS60',message='Workforce access is not allowed'; end if;
return jsonb_build_object('locations',coalesce((select jsonb_agg(jsonb_build_object('id',l.id,'code',l.code::text,'name',l.name,'kind',l.kind,'timezone',l.timezone,'isActive',l.is_active) order by l.name) from app.locations l where l.tenant_id=p_tenant_id),'[]'::jsonb),'roles',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'code',r.code::text,'name',r.name,'isSystemTemplate',r.is_system_template,'permissions',(select coalesce(jsonb_agg(rp.permission_code order by rp.permission_code),'[]'::jsonb) from app.role_permissions rp where rp.tenant_id=r.tenant_id and rp.role_id=r.id)) order by r.name) from app.roles r where r.tenant_id=p_tenant_id),'[]'::jsonb),'employees',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'employeeCode',e.employee_code::text,'displayName',e.display_name,'status',e.status,'hasPosPin',c.employee_id is not null,'roleIds',(select coalesce(jsonb_agg(mr.role_id),'[]'::jsonb) from app.membership_roles mr where mr.tenant_id=e.tenant_id and mr.user_id=e.user_id),'locationIds',(select coalesce(jsonb_agg(el.location_id),'[]'::jsonb) from app.employee_locations el where el.tenant_id=e.tenant_id and el.employee_id=e.id)) order by e.display_name) from app.employees e left join app.employee_pos_credentials c on c.tenant_id=e.tenant_id and c.employee_id=e.id where e.tenant_id=p_tenant_id),'[]'::jsonb),'registers',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'locationId',r.location_id,'locationName',l.name,'code',r.code::text,'name',r.name,'status',r.status) order by l.name,r.name) from app.registers r join app.locations l on l.tenant_id=r.tenant_id and l.id=r.location_id where r.tenant_id=p_tenant_id),'[]'::jsonb)); end; $$;

create function app.create_location(p_actor_user_id uuid,p_tenant_id uuid,p_code text,p_name text,p_kind text,p_timezone text,p_idempotency_key text,p_request_hash text,p_request_id text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_id uuid;v_response jsonb; begin if not exists(select 1 from app.tenant_memberships where tenant_id=p_tenant_id and user_id=p_actor_user_id and status='active' and is_owner) then raise exception using errcode='HCS60',message='Owner access is required'; end if; if p_kind not in('store','warehouse','office','virtual') then raise exception using errcode='HCS61',message='Location details are invalid'; end if; insert into app.locations(tenant_id,code,name,kind,timezone) values(p_tenant_id,btrim(p_code),btrim(p_name),p_kind,coalesce(nullif(btrim(p_timezone),''),'Asia/Manila')) returning id into v_id; v_response=jsonb_build_object('locationId',v_id,'status','created'); insert into audit.audit_events(tenant_id,request_id,actor_type,actor_id,action,entity_type,entity_id) values(p_tenant_id,p_request_id,'tenant_user',p_actor_user_id,'location.created','location',v_id); return v_response; exception when unique_violation then raise exception using errcode='HCS62',message='Location code already exists'; end; $$;

create function app.create_employee(p_actor_user_id uuid,p_tenant_id uuid,p_employee_code text,p_display_name text,p_role_id uuid,p_location_ids jsonb,p_pin text,p_idempotency_key text,p_request_hash text,p_request_id text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_id uuid;v_location jsonb;v_response jsonb; begin if not exists(select 1 from app.tenant_memberships where tenant_id=p_tenant_id and user_id=p_actor_user_id and status='active' and is_owner) then raise exception using errcode='HCS60',message='Owner access is required'; end if; if p_pin !~ '^[0-9]{4,6}$' then raise exception using errcode='HCS63',message='POS PIN must contain 4 to 6 digits'; end if; if not exists(select 1 from app.roles where tenant_id=p_tenant_id and id=p_role_id) then raise exception using errcode='HCS64',message='Role was not found'; end if; insert into app.employees(tenant_id,employee_code,display_name,status) values(p_tenant_id,btrim(p_employee_code),btrim(p_display_name),'active') returning id into v_id; insert into app.employee_pos_credentials(tenant_id,employee_id,pin_hash) values(p_tenant_id,v_id,extensions.crypt(p_pin,extensions.gen_salt('bf',10))); for v_location in select * from jsonb_array_elements(p_location_ids) loop insert into app.employee_locations(tenant_id,employee_id,location_id) values(p_tenant_id,v_id,(v_location#>>'{}')::uuid); end loop; v_response=jsonb_build_object('employeeId',v_id,'status','created'); insert into audit.audit_events(tenant_id,request_id,actor_type,actor_id,action,entity_type,entity_id) values(p_tenant_id,p_request_id,'tenant_user',p_actor_user_id,'employee.created','employee',v_id); return v_response; exception when unique_violation then raise exception using errcode='HCS65',message='Employee code already exists'; end; $$;

create function app.create_register(p_actor_user_id uuid,p_tenant_id uuid,p_location_id uuid,p_code text,p_name text,p_idempotency_key text,p_request_hash text,p_request_id text) returns jsonb language plpgsql security definer set search_path='' as $$ declare v_id uuid;v_response jsonb; begin if not exists(select 1 from app.tenant_memberships where tenant_id=p_tenant_id and user_id=p_actor_user_id and status='active' and is_owner) then raise exception using errcode='HCS60',message='Owner access is required'; end if; if not exists(select 1 from app.locations where tenant_id=p_tenant_id and id=p_location_id and is_active) then raise exception using errcode='HCS66',message='Location was not found'; end if; insert into app.registers(tenant_id,location_id,code,name) values(p_tenant_id,p_location_id,btrim(p_code),btrim(p_name)) returning id into v_id; v_response=jsonb_build_object('registerId',v_id,'status','created'); insert into audit.audit_events(tenant_id,request_id,actor_type,actor_id,action,entity_type,entity_id,location_id) values(p_tenant_id,p_request_id,'tenant_user',p_actor_user_id,'register.created','register',v_id,p_location_id); return v_response; exception when unique_violation then raise exception using errcode='HCS67',message='Register code already exists'; end; $$;

create or replace function app.create_employee(p_actor_user_id uuid,p_tenant_id uuid,p_employee_code text,p_display_name text,p_role_id uuid,p_location_ids jsonb,p_pin text,p_idempotency_key text,p_request_hash text,p_request_id text) returns jsonb language plpgsql security definer set search_path='' as $$
declare v_id uuid;v_location jsonb;v_response jsonb;
begin
 if not exists(select 1 from app.tenant_memberships where tenant_id=p_tenant_id and user_id=p_actor_user_id and status='active' and is_owner) then raise exception using errcode='HCS60',message='Owner access is required'; end if;
 if p_pin !~ '^[0-9]{4,6}$' then raise exception using errcode='HCS63',message='POS PIN must contain 4 to 6 digits'; end if;
 if not exists(select 1 from app.roles where tenant_id=p_tenant_id and id=p_role_id) then raise exception using errcode='HCS64',message='Role was not found'; end if;
 insert into app.employees(tenant_id,employee_code,display_name,status) values(p_tenant_id,btrim(p_employee_code),btrim(p_display_name),'active') returning id into v_id;
 insert into app.employee_roles(tenant_id,employee_id,role_id) values(p_tenant_id,v_id,p_role_id);
 insert into app.employee_pos_credentials(tenant_id,employee_id,pin_hash) values(p_tenant_id,v_id,extensions.crypt(p_pin,extensions.gen_salt('bf',10)));
 for v_location in select * from jsonb_array_elements(p_location_ids) loop insert into app.employee_locations(tenant_id,employee_id,location_id) values(p_tenant_id,v_id,(v_location#>>'{}')::uuid); end loop;
 v_response=jsonb_build_object('employeeId',v_id,'status','created'); insert into audit.audit_events(tenant_id,request_id,actor_type,actor_id,action,entity_type,entity_id) values(p_tenant_id,p_request_id,'tenant_user',p_actor_user_id,'employee.created','employee',v_id); return v_response;
exception when unique_violation then raise exception using errcode='HCS65',message='Employee code already exists'; end; $$;

revoke all on function app.list_workforce_context(uuid,uuid),app.create_location(uuid,uuid,text,text,text,text,text,text,text),app.create_employee(uuid,uuid,text,text,uuid,jsonb,text,text,text,text),app.create_register(uuid,uuid,uuid,text,text,text,text,text) from public,anon,authenticated;
grant execute on function app.list_workforce_context(uuid,uuid),app.create_location(uuid,uuid,text,text,text,text,text,text,text),app.create_employee(uuid,uuid,text,text,uuid,jsonb,text,text,text,text),app.create_register(uuid,uuid,uuid,text,text,text,text,text) to hcs_hyperdrive;
commit;
