/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=development --include-runtime=false` (hash: e7b5dee4f5afadbb96cf29dc7793f99a)
interface __BaseEnv_Env {
  HYPERDRIVE: Hyperdrive
  ENVIRONMENT: 'development'
  SUPABASE_URL: 'https://nlrzdgcxydmcvhushzwv.supabase.co'
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index')
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string
}
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'ENVIRONMENT' | 'SUPABASE_URL'>> {}
}
